on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  main:
    if: "github.event.action != 'labeled' || github.event.label.name == 'pre-commit ci run'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr edit ${{ github.event.number }} --remove-label 'pre-commit ci run'
        if: github.event.action == 'labeled' && github.event.label.name == 'pre-commit ci run'
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0
        with:
          version: "3.16.3"
      - name: Build dependencies
        run: |
          helm dependency update
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
